#!/bin/bash
# GT Mesh — Initialize this GT as a mesh node
#
# Usage: mesh-init.sh [--role coordinator|worker] [--name <name>] [--github <username>] [--email <email>]

# No set -e — we handle errors explicitly to avoid false failures
# from dolt operations that return non-zero for benign reasons

GT_ROOT="${GT_ROOT:-.}"
MESH_YAML="${MESH_YAML:-$GT_ROOT/mesh.yaml}"
DOLTHUB_DB="${DOLTHUB_DB:-deepwork/gt-agent-mail}"
CLONE_DIR="/tmp/mesh-sync-clone"

# Parse args
ROLE="coordinator"
GT_NAME=""
OWNER_NAME=""
OWNER_GITHUB=""
OWNER_EMAIL=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --role) ROLE="$2"; shift 2 ;;
    --name) GT_NAME="$2"; shift 2 ;;
    --github) OWNER_GITHUB="$2"; shift 2 ;;
    --email) OWNER_EMAIL="$2"; shift 2 ;;
    --owner) OWNER_NAME="$2"; shift 2 ;;
    --db) DOLTHUB_DB="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

echo "==========================================="
echo "  GT Mesh — Node Initialization"
echo "==========================================="
echo ""

# Validate role
if [[ "$ROLE" != "coordinator" && "$ROLE" != "worker" && "$ROLE" != "contributor" ]]; then
  echo "[error] Role must be: coordinator, worker, or contributor"
  exit 1
fi

# Auto-detect GT name if not provided
if [ -z "$GT_NAME" ]; then
  if [ -f "$GT_ROOT/mayor/town.json" ]; then
    GT_NAME=$(python3 -c "import json; print(json.load(open('$GT_ROOT/mayor/town.json')).get('name', ''))" 2>/dev/null || true)
  fi
  if [ -z "$GT_NAME" ]; then
    GT_NAME="gt-$(hostname -s 2>/dev/null || echo 'unknown')"
  fi
fi

# Collect identity if not provided
if [ -z "$OWNER_NAME" ]; then
  OWNER_NAME=$(git config --global user.name 2>/dev/null || echo "")
  if [ -z "$OWNER_NAME" ]; then
    echo "[error] Could not detect owner name. Use --owner flag or set git config user.name"
    exit 1
  fi
fi

if [ -z "$OWNER_GITHUB" ]; then
  echo "[error] GitHub username is required. Use --github <username>"
  echo "        This is MANDATORY for contributor attribution."
  exit 1
fi

if [ -z "$OWNER_EMAIL" ]; then
  OWNER_EMAIL=$(git config --global user.email 2>/dev/null || echo "")
  if [ -z "$OWNER_EMAIL" ]; then
    echo "[error] Could not detect git email. Use --email flag or set git config user.email"
    exit 1
  fi
fi

# Warn if email looks like a placeholder
if echo "$OWNER_EMAIL" | grep -qE "(gasclaw\.local|noreply@|localhost)"; then
  echo "[warn] Email '$OWNER_EMAIL' may not be linked to GitHub."
  echo "       Commits with this email won't show in the contributors graph."
  echo "       Consider using: <github-id>+${OWNER_GITHUB}@users.noreply.github.com"
fi

echo "[1/4] Identity"
echo "       GT Name:  $GT_NAME"
echo "       Role:     $ROLE"
echo "       Owner:    $OWNER_NAME"
echo "       GitHub:   $OWNER_GITHUB"
echo "       Email:    $OWNER_EMAIL"
echo ""

# Check if already initialized
if [ -f "$MESH_YAML" ]; then
  echo "[ok] mesh.yaml already exists at $MESH_YAML"
  echo "      Skipping mesh.yaml generation (preserving custom config)"
  echo ""
  SKIP_YAML=true
else
  SKIP_YAML=false
fi

# Generate mesh.yaml (only if it doesn't exist)
echo "[2/4] Writing mesh.yaml..."
if [ "$SKIP_YAML" = true ]; then
  echo "       Preserved existing mesh.yaml"
else
cat > "$MESH_YAML" <<YAML
# GT Mesh Configuration
# Generated by: gt mesh init --role $ROLE
# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)

instance:
  id: "$GT_NAME"
  name: "$GT_NAME"
  role: "$ROLE"
  owner:
    name: "$OWNER_NAME"
    email: "$OWNER_EMAIL"
    github: "$OWNER_GITHUB"

dolthub:
  org: "deepwork"
  database: "gt-agent-mail"
  sync_interval: "2m"
  clone_dir: "$CLONE_DIR"

rules:
  branch_format: "gt/{id}/{issue}-{desc}"
  pr_target: "dev"
  commit_format: "conventional"
  require_issue_reference: true
  max_concurrent_claims: 3
  require_review: true
  no_force_push: true
  no_secrets_in_commits: true

daemon:
  enabled: true
  sync_interval: "2m"
  auto_claim:
    enabled: false
    max_concurrent: 2

feed:
  delivery: "digest"
  digest_interval: "30m"
YAML
echo "       Written to $MESH_YAML"
fi
echo ""

# Set up DoltHub sync clone
echo "[3/4] Setting up DoltHub sync..."
if ! command -v dolt &>/dev/null; then
  echo "[error] Dolt is not installed. Install it: https://docs.dolthub.com/introduction/installation"
  exit 1
fi

if [ -d "$CLONE_DIR/.dolt" ]; then
  echo "       Sync clone exists at $CLONE_DIR"
  cd "$CLONE_DIR"
  dolt pull 2>/dev/null || true
  # Auto-resolve any merge conflicts (prefer remote — ours is about to be re-inserted anyway)
  if dolt conflicts cat . 2>/dev/null | grep -q "." 2>/dev/null; then
    echo "       Resolving sync conflicts..."
    dolt conflicts resolve --theirs . 2>/dev/null || true
    dolt add . 2>/dev/null
    dolt commit -m "mesh: auto-resolve conflicts on init" --allow-empty 2>/dev/null || true
  fi
  cd - >/dev/null
else
  echo "       Cloning $DOLTHUB_DB..."
  rm -rf "$CLONE_DIR" 2>/dev/null || true
  dolt clone "$DOLTHUB_DB" "$CLONE_DIR" 2>/dev/null || {
    echo "[error] Failed to clone DoltHub database."
    echo "       Check your Dolt credentials: dolt creds ls"
    echo "       Ensure you have access to $DOLTHUB_DB"
    exit 1
  }
fi
echo "       DoltHub sync ready"
echo ""

# Register as peer
echo "[4/4] Registering as mesh peer..."
cd "$CLONE_DIR"

# Check if peers table exists
if ! dolt sql -q "SELECT 1 FROM peers LIMIT 1;" -r csv 2>/dev/null | grep -q "1"; then
  echo "       Creating peers table..."
  dolt sql -q "CREATE TABLE IF NOT EXISTS peers (gt_id VARCHAR(64) PRIMARY KEY, name VARCHAR(128), owner VARCHAR(128), role VARCHAR(32), status VARCHAR(32) DEFAULT 'active', dolt_pubkey VARCHAR(128), capabilities JSON, joined_at DATETIME, last_seen DATETIME, expires_at DATETIME, invited_by VARCHAR(64), metadata JSON);" 2>/dev/null
fi

# Get Dolt pubkey
DOLT_PUBKEY=$(dolt creds ls 2>/dev/null | grep "^  " | head -1 | awk '{print $1}' || echo "unknown")

# Upsert peer (idempotent)
dolt sql -q "REPLACE INTO peers (gt_id, name, owner, role, status, dolt_pubkey, joined_at, last_seen, metadata) VALUES ('$GT_NAME', '$GT_NAME', '$OWNER_NAME <$OWNER_EMAIL>', '$ROLE', 'active', '$DOLT_PUBKEY', NOW(), NOW(), JSON_OBJECT('github', '$OWNER_GITHUB'));" 2>/dev/null

dolt add . 2>/dev/null || true
dolt commit -m "mesh: register peer $GT_NAME ($ROLE)" --allow-empty 2>/dev/null || true
dolt push 2>/dev/null || echo "       [warn] Push deferred — will sync on next cron cycle"

cd "$GT_ROOT"
echo "       Registered as '$GT_NAME' (role: $ROLE)"
echo ""

echo "==========================================="
echo "  GT Mesh initialized!"
echo "==========================================="
echo ""
echo "  Config:  $MESH_YAML"
echo "  Sync:    $CLONE_DIR"
echo "  Role:    $ROLE"
echo "  GT ID:   $GT_NAME"
echo ""
if [ "$ROLE" = "coordinator" ]; then
  echo "  Next: gt mesh invite --role write --expires 7d"
else
  echo "  Next: gt mesh inbox   (check for work)"
fi
echo ""
